name: 'Complies to 42-Norm'
on: [push, workflow_dispatch]

jobs:
  norminette-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: src include
